apiVersion: v1
kind: Pod
metadata:
  labels:
    app: testapp
    feature: "20220207135452"
  name: debug-network-pod2022020322161120220207135452
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: testapp:20220203221611
    name: debug-network-container
