apiVersion: v1
kind: Pod
metadata:
  labels:
    app: testapp
    feature: "20220207205226"
  name: debug-network-pod20220207205226
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: testapp:20220207205226
    name: debug-network-container
