apiVersion: v1
kind: Pod
metadata:
  labels:
    app: testapp
    feature: "20220203221611"
  name: debug-network-pod2022020215420820220203221611
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: testapp:20220202154208
    name: debug-network-container
