apiVersion: v1
kind: Pod
metadata:
  labels:
    app: testapp
    feature: "20220202154208"
  name: debug-network-pod20220202154208
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: testapp:20220202154208
    name: debug-network-container
