apiVersion: v1
kind: Pod
metadata:
  labels:
    app: testapp
  name: debug-network-pod
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: testapp:20220222092934
    name: debug-network-container
